### ISSUE TITLE
status　'TODAY' | 'TOMORROW' | 'NEXT'　へのカスタムバリデーション作成

### ISSUE THREAD

**Issue by mu0363** [qin-team-k/qin-todo-backend#24]
statusが'TODAY' | 'TOMORROW' | 'NEXT'以外の値が入った場合に500エラーになってしまってるので、カスタムバリデーションをする必要ありそうです。
カスタムバリデーションをする場合は、下記は不要になります。
一旦コメントで`FIXME カスタムバリデーション追加`などにしておいてもらえると助かります 🙇🏻 
```ts
@IsString()
@IsNotEmpty()
@MaxLength(8)
```

_Originally posted by @magatakohei in https://github.com/qin-team-k/qin-todo-backend/pull/20#discussion_r815845115_

**Comment by magatakohei** [comment]
参考
https://github.com/typestack/class-validator/issues/159
