### ISSUE TITLE
削除、order変更時idsがなくなった場合にnullにする

### ISSUE THREAD

**Issue by mu0363** [qin-team-k/qin-todo-backend#26]
> todoIds をString? として null許容にしました。
ただprisma studioでテーブル確認すると空のままなので本当にnullなのかどうか不明です...
一応公式には下記の記載があるのですが。

null許容にはなっています。テストデータ作成時に空文字を指定せずに、nullを入れれば良いかと思います。
また、削除やorderを変えたときにidsがなくなった場合にnullにする必要があります（後でも大丈夫です。）

<img width="751" alt="image" src="https://user-images.githubusercontent.com/65271262/156120436-96764bd0-19a5-471b-8cce-54fe8a22e86a.png">

_Originally posted by @magatakohei in https://github.com/qin-team-k/qin-todo-backend/issues/20#issuecomment-1055092329_

**Comment by magatakohei** [comment]
- [ ] todo削除時にTodoOrderのidsが空であればnullを設定する
- [ ] todo並び替え時に移動前のstatusのidsが空であればnullを設定する
- [ ] seedのidsが存在しない場合のテストデータは `todoIds: null`とする
